a=("\t\tLEAVE LETTER")
print(a)
b=("-------------------------------------------")
print(b)
c=str(input("enter from"))
print("From",c)
d=str(input("enter to"))
print("To",d)
e=("Respected sir,")
print(e)
f=str(input("body of letter"))
print("body of letter",f)
g=("\t\tThanking You")
print(g)
h=("Date:28.04,2023\t\t\t\t\tYours faithfully,")
print(h)
i=("Place:Puducherry\t\t\t\tN.Pavithra")
